name: release build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            9.0.x
          global-json-file: ./framework/global.json
      - name: Build
        run: dotnet build -c Release --no-restore
        working-directory: ./framework/src/
      - name: Pack NuGet
        run: dotnet pack -c Release -o ./  -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - name: Push NuGet
        run: dotnet nuget push '*.nupkg' -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
